language: python

python:
    - 3.6

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:
    - conda env create -f environment.yaml

before_script:
    - chmod 755 test.sh
    - conda activate star-htseq

script: ./test.sh
