name: star-htseq
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.6
    - pandas 

    - star
    - samtools
    - htseq

    - pip
    - pip:
        - snakemake==5.8.2
